Feat/block local
Wiredcraft/DoKit pull request #2
Opened 2022-11-14 10:27 UTC by cynthiaxie

1. remove data upload
2. change block threshold millis to configurable
3. save block info to local files

2022-11-18 00:00 UTC, seazon requested changes

2022-11-18 00:00 UTC, seazon commented on Android/dokit/src/main/java/com/didichuxing/doraemonkit/datapick/DataPickManager.java
> +//        Request requset = new JsonObjectRequest(Request.Method.POST, NetworkManager.APP_DATA_PICK_URL, new JSONObject(content), response -> {
remove these codes

2022-11-18 00:12 UTC, seazon commented
pls don't submit [Revert "feat: remove upload user info and data pick info and app heal…](https://github.com/Wiredcraft/DoKit/pull/2/commits/70c4320fe1253323dced9af79cbf8fdb7baa4de7) such revert code

your commits should be only 3
[feat: save block info to local files](https://github.com/Wiredcraft/DoKit/pull/2/commits/942c214e0ad5effb103269ce4da48c30fa831c16)
~[feat: remove upload user info and data pick info and app health info](https://github.com/Wiredcraft/DoKit/pull/2/commits/0e9447c08eca83388062c0067c5e7786cf4b29bc)~
[feat: change block threshold millis to configurable, config it when D…](https://github.com/Wiredcraft/DoKit/pull/2/commits/e2012d11c33c7661236218ec86fe6855f1d16fd7) 
~[Revert "feat: remove upload user info and data pick info and app heal…](https://github.com/Wiredcraft/DoKit/pull/2/commits/70c4320fe1253323dced9af79cbf8fdb7baa4de7)~
[feat: not upload data pick info、app base info and app health info any…](https://github.com/Wiredcraft/DoKit/pull/2/commits/46fdfab54fae75aa701a0e06915be46edcd2fabc) 

you can drop commit via Drop Commit in Android Studio Git view, or use Git command.

2022-11-18 02:16 UTC, cynthiaxie commented on Android/dokit/src/main/java/com/didichuxing/doraemonkit/util/DoraemonStatisticsUtil.java
> +        //app 启动数据埋点
ok

2022-11-21 05:59 UTC, closed without merging

2022-11-24 03:10 UTC, seazon commented
new PR created: https://github.com/Wiredcraft/DoKit/pull/3